project:
  type: website
  output-dir: docs

website:
  title: "Immunoassay Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Immunoassay Project
      - href: RTD.qmd
        text: RTD Overview
      - href: sop.qmd
        text: Standard Operating Procedure
      - href: process.qmd
        text: Product Overview
      - href: project.qmd
        text: Project Overview
  page-footer:
    left: "Â© 2025 Immunoassay Research Group"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: default
    toc: true
    toc-depth: 2
